apiVersion: v1
kind: Service
metadata:
  name: vpn-pritunl-udp
spec:
  type: NodePort
  ports:
    - name: "udp"
      port: 1194
      protocol: TCP
      targetPort: 1194 
  selector:
    app: vpn-pritunl
