apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: pritunl
spec:
  ports:
    - port: 31121
      targetPort: 31121
  selector:
    app: pritunl
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: pritunl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: pritunl
spec:
  selector:
    matchLabels:
      app: pritunl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pritunl
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
        - name: Mongo_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-pass
              key: password
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
